#!/bin/sh
cat << __EOC__
$ ./configure  '--with-readline=/usr/include/readline/' '--disable-conio' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--with-scriptdir=/etc/bacula/scripts' '--with-working-dir=/var/lib/bacula' '--with-logdir=/var/log' '--enable-smartalloc' '--with-postgresql' '--with-archivedir=/mnt/backup' '--enable-readline'

Configuration on Wed Aug 22 15:21:32 BRT 2018:

   Host:		     x86_64-pc-linux-gnu -- redhat 
   Bacula version:	     Bacula 9.2.0 (20 July 2018)
   Source code location:     .
   Install binaries:	     /usr/sbin
   Install libraries:	     /usr/lib64
   Install config files:     /etc/bacula
   Scripts directory:	     /etc/bacula/scripts
   Archive directory:	     /mnt/backup
   Working directory:	     /var/lib/bacula
   PID directory:	     /var/run
   Subsys directory:	     /var/lock/subsys
   Man directory:	     ${datarootdir}/man
   Data directory:	     /usr/share
   Plugin directory:	     /usr/lib64
   C Compiler:		     gcc 4.4.7
   C++ Compiler:	     /usr/bin/g++ 4.4.7
   Compiler flags:	      -g -O2 -Wall -x c++ -fno-strict-aliasing -fno-exceptions -fno-rtti
   Linker flags:	      
   Libraries:		     -lpthread -ldl -ldl 
   Statically Linked Tools:  no
   Statically Linked FD:     no
   Statically Linked SD:     no
   Statically Linked DIR:    no
   Statically Linked CONS:   no
   Database backends:	     PostgreSQL
   Database port:	      
   Database name:	     bacula
   Database user:	     bacula
   Database SSL options:     

   Job Output Email:	     root@localhost
   Traceback Email:	     root@localhost
   SMTP Host Address:	     localhost

   Director Port:	     9101
   File daemon Port:	     9102
   Storage daemon Port:      9103

   Director User:	     
   Director Group:	     
   Storage Daemon User:      
   Storage DaemonGroup:      
   File Daemon User:	     
   File Daemon Group:	     

   Large file support:	     yes
   Bacula conio support:     no -lreadline -lhistory -ltinfo
   readline support:	     yes 
   TCP Wrappers support:     no 
   TLS support: 	     no
   Encryption support:	     no
   ZLIB support:	     no
   LZO support: 	     no
   enable-smartalloc:	     yes
   enable-lockmgr:	     no
   bat support: 	     no
   client-only: 	     no
   build-dird:		     yes
   build-stored:	     yes
   Plugin support:	     yes
   AFS support: 	     no
   ACL support: 	     no
   XATTR support:	     yes
   systemd support:	     no 
   Batch insert enabled:     PostgreSQL

  
__EOC__
